# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[es]
  languageCode = "es"
  contentDir = "content/es"
  title = "Biodiversidata"
  [es.params]
    description = "Consorcio de Datos de Biodiversidad del Uruguay"
  [[es.menu.main]]
    name = "Inicio"
    url = "#hero"
    weight = 10
  [[es.menu.main]]
    name = "Novedades"
    url = "#posts"
    weight = 20
  [[es.menu.main]]
    name = "Integrantes"
    url = "#people"
    weight = 30
  [[es.menu.main]]
    name = "Recursos"
    url = "#projects"
    weight = 40
  [[es.menu.main]]
    name = "Publicaciones"
    url = "#publications"
    weight = 50
  [[es.menu.main]]
    name = "Contacto"
    url = "#contact"
    weight = 60
  [[es.menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 70