# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Aerial"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://github.com/sethmacleod/aerial/blob/master/LICENSE.md"
description = "Ported theme of HTML5 UP's Aerial: a single page, single screen responsive site template."
homepage = "https://github.com/sethmacleod/aerial"
tags = ["responsive", "personal"]
features = ["responsive"]
min_version = 0.18

[author]
  name = "Seth MacLeod"
  homepage = "https://www.sethmacleod.com/"

# If porting an existing theme
[original]
  name = "@ajlkn"
  homepage = "https://html5up.net/aerial"
  repo = ""
