languageCode = "en-us"
title = "Biodiversidata"
baseurl = "/"
theme = "aerial"

[params]
  name = "Biodiversidata"
  about = "Uruguayan Consortium of Biodiversity Data"
  copyright = "Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "not"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/biodiversidata"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:fGrattarola@lincoln.ac.uk"