baseURL = "/"
languageCode = "en-us"
title = "Biodiversidata - Uruguayan Consortium of Biodiversity Data"
theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Service"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Portfolio"
    URL = "portfolio"
    weight = 4

    [[menu.nav]]
    name = "Team"
    URL = "our-team"
    weight = 5

    [[menu.nav]]
    name = "Pricing"
    URL = "pricing"
    weight = 6

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Home"
logo = "images/logo.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBI14J_PNWVd-m0gnUBkjmhoQyNyd7nllA"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/slider-01.jpg"
    icon = ""
    heading = ""
    content= ""
    btn = false
    btnText="About"
    btnURL="#about"

    # call to action
    [params.cta]
    enable = false
    title = "Great Design & Incredible Features"
    content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis tenetur odio impedit incidunt? Omnis accusantium ea reiciendis, fugit commodi nostrum."
    btnURL = "#"
    btnText = "Start a project with us"

    # counter
    [params.counter]
    enable = false
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Species of Amphibia"
        icon = "tf-ion-android-happy"
        count = "51"

        [[params.counter.counterItem]]
        title = "Species of Aves"
        icon = "tf-ion-archive"
        count = "442"

        [[params.counter.counterItem]]
        title = "Species of Mammalia"
        icon = "tf-ion-thumbsup"
        count = "115"

        [[params.counter.counterItem]]
        title = "Species of Reptilia"
        icon = "tf-ion-coffee"
        count = "68"
    
    # footer
    [params.footer]
        copyright = "Biodiversidata"
        copyrightURL = "www.flograttarola.com"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "https://twitter.com/biodiversidata"
        
