baseURL = "/"
languageCode = "en-us"
title = "Biodiversidata"
#themesDir = "../.."
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2
    
[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'About'
  homepage_intro = 'Uruguayan Consortium of Biodiversity Data'
  homepage_image = '/images/terminal.gif'

  [params.homepage_meta_tags]
    meta_description = "Biodiversidata is funded by ANII"
    meta_og_title = "Biodiversidata"
    meta_og_type = "website"
    meta_og_url = "https://biodiversidata.org"
    meta_og_image = "/images/biodiversidata-perfil.svg"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = ""
    meta_twitter_site = "@flograttarola"
    meta_twitter_creator = "@flograttarola"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
